### ISSUE TITLE
Handle database and amazon work

### ISSUE THREAD

**Issue by salih997** [bounswe/2021SpringGroup5#174]
We will handle database and amazon issues. With @e7hdk @berkaybor

**Comment by GozdeUnver** [comment]
I reviewed @salih997 's first attempt of deployment. He used my "gozdebranch" and I tested whether it was working. It was working very well. In my weatherCondition app I used database and in this deployment, database was working as it should.

**Comment by GozdeUnver** [comment]
@berkaybor asked why we had programming error when we deployed our project and I reviewed and commented that it was because we hadn't called "makemigrations" and "migrate" commands.

**Comment by berkaybor** [comment]
Salih started an AWS EC2 instance and installed docker using snap. I had to delete and reinstall it because it was giving a version error. I added [Dockerfile](https://github.com/bounswe/2021SpringGroup5/blob/master/practice-app/group5_api/Dockerfile) and [docker-compose.yml](https://github.com/bounswe/2021SpringGroup5/blob/master/practice-app/group5_api/docker-compose.yml) following official documentation. When I first started the server, there were a few errors. I fixed easy errors in urls.py files and made migrations. Now app is opening on [3.127.142.97:8000](http://3.127.142.97:8000/) but some modules are not working correctly, we need to fix them.

**Comment by zudiay** [comment]
I see the Daily Quote API is not working. Do you have any idea why?

**Comment by GozdeUnver** [comment]
When we change database settings like this 'HOST': '','PORT': '5432', it worked but it used to be 'HOST': 'db' was that on purpose that I missed?

**Comment by zudiay** [comment]
It works on my machine when i run it via Docker :( Still couldn't figure out why it is not working in the server

**Comment by berkaybor** [comment]
I restarted the server via docker-compose down and docker-compose up commands. It is working fine now.

**Comment by zudiay** [comment]
Epic moment... Thanks Berkay!

![tenor](https://user-images.githubusercontent.com/48058901/121438109-1af80b80-c98c-11eb-8856-b437d6edf889.gif)

**Comment by atasoyfurkan** [comment]
I am late to add command because I mentioned it in different issue(#209) but I correct docker-compose adding some part to it, and I also add some new feature to it to get it to final shape. It is now in final shape and can be found in project directory.
