### ISSUE TITLE
Create mockup (event details page)

### ISSUE THREAD

**Issue by salih997** [bounswe/2021SpringGroup5#65]

**Comment by zudiay** [comment]
The first draft has arrived. You can see the pages below:

1) The first page is My Events page of the user. Users see the events they have created here. There are two tabs: upcoming and past events. The user sees the basic information here and can go to the detail page using the button. This page is scrollable.
<img width="300" alt="my_events" src="https://user-images.githubusercontent.com/48058901/115124893-8dbcba00-9fcd-11eb-927b-661a735fe1c4.png">

2) As user clicks the "View Details" page of the above mock-up, they arrive to this page. This page allows the user to edit the information about the event. This page is scrollable. The creator can cancel the event or view the participant details. 

<img width="300" alt="event_detail_1" src="https://user-images.githubusercontent.com/48058901/115124991-1a677800-9fce-11eb-84d3-96ca60716ae1.png">

<img width="300" alt="event_detail_2" src="https://user-images.githubusercontent.com/48058901/115125017-33702900-9fce-11eb-92f3-d5e2ec549359.png">

3) The user can see the participants in a different page. There are different tabs according to the acceptance status of the participants. The creator can change the acceptance status or view users' profiles. 
<img width="300" alt="participants" src="https://user-images.githubusercontent.com/48058901/115125057-7205e380-9fce-11eb-9de1-e3478c7d8160.png">

4) The user can see the participant analytics here, again with respect to the acceptance status. Analytics provided may be enlarged. 
<img width="300" alt="analytics" src="https://user-images.githubusercontent.com/48058901/115125102-b72a1580-9fce-11eb-85e5-97c5f1549d7e.png">

**Comment by zudiay** [comment]
There are some missing parts like the scroll bar, going back button, change image button, etc. I am also not sure about the spectator page, whether it should be a different part or a tab in the participants page. I'm going to update these. Footer and header may be added as Umut provides them

**Comment by zudiay** [comment]
I handled the missing parts :) I'm uploading the updated images now.

1) I added scroll bar and going back button to this page. 
<img width="300" alt="Screen Shot 2021-04-18 at 10 59 30" src="https://user-images.githubusercontent.com/48058901/115138534-7ca79380-a035-11eb-8668-8cf72e6deedc.png">

2) I added participant count. I also added change image icon, change name icon and a scroll bar.
<img width="300" alt="Screen Shot 2021-04-18 at 10 59 45" src="https://user-images.githubusercontent.com/48058901/115138555-9c3ebc00-a035-11eb-8a20-717fc364e760.png">
<img width="300" alt="Screen Shot 2021-04-18 at 10 59 56" src="https://user-images.githubusercontent.com/48058901/115138580-c3958900-a035-11eb-802c-e16230e0885e.png">

3) I thought it would be better to see the spectators as a tab rather than a page. So it's added here. I also made some naming changes. The counts are also visible. I added a border to each profile page indicating the current status of the user (waiting (grey), accepted(green), rejected(red)). Status is also written as text below the username.
<img width="300" alt="Screen Shot 2021-04-18 at 11 00 08" src="https://user-images.githubusercontent.com/48058901/115138613-ea53bf80-a035-11eb-8b86-0de6215c5694.png">

As the user clicks accept, the accepted user's status changes. The counts are updated and the accept button related to that user turns into a withdraw button. The withdraw button takes a user from accepted or rejected states back to waiting state. 
<img width="300" alt="Screen Shot 2021-04-18 at 11 00 19" src="https://user-images.githubusercontent.com/48058901/115138702-60582680-a036-11eb-962a-6628bd481885.png">

4) I changed the tabs for the analytics page as in other pages 
<img width="300" alt="Screen Shot 2021-04-18 at 11 00 49" src="https://user-images.githubusercontent.com/48058901/115138726-867dc680-a036-11eb-87f3-b276dc3ab921.png">

**Comment by zudiay** [comment]
Again, updates... I added footer Umut provided to all pages and I also added some navigation pointers for the scenario. There are some additional changeS:
1) Added live events tab. Also some naming changes
<img width="300" alt="Screen Shot 2021-04-18 at 14 06 06" src="https://user-images.githubusercontent.com/48058901/115143558-bf2a9980-a050-11eb-8077-32c0b1d977b6.png">
2) Added postpone option to cancel button. Added event status option.
<img width="300" alt="Screen Shot 2021-04-18 at 14 06 19" src="https://user-images.githubusercontent.com/48058901/115143571-d6698700-a050-11eb-921d-e9c34aa567ff.png">
<img width="300" alt="Screen Shot 2021-04-18 at 14 07 14" src="https://user-images.githubusercontent.com/48058901/115143600-0d3f9d00-a051-11eb-979e-34d4a2e8cb68.png">
3) Nothing additional, only footer & navigation pointers.
<img width="300" alt="Screen Shot 2021-04-18 at 14 07 21" src="https://user-images.githubusercontent.com/48058901/115143648-4a0b9400-a051-11eb-88d1-a1148abdea1d.png">
<img width="300" alt="Screen Shot 2021-04-18 at 14 07 28" src="https://user-images.githubusercontent.com/48058901/115143654-4d068480-a051-11eb-9b4f-406e268b30a8.png">
<img width="300" alt="Screen Shot 2021-04-18 at 14 07 36" src="https://user-images.githubusercontent.com/48058901/115143659-50017500-a051-11eb-805b-9d92a51631ed.png">
<img width="300" alt="Screen Shot 2021-04-18 at 14 07 53" src="https://user-images.githubusercontent.com/48058901/115143660-51cb3880-a051-11eb-9851-38af606448a7.png">

4) Nothing additional, only footer & navigation pointers.
<img width="300" alt="Screen Shot 2021-04-18 at 14 08 06" src="https://user-images.githubusercontent.com/48058901/115143690-7fb07d00-a051-11eb-8597-9da14f8c654f.png">

**Comment by zudiay** [comment]
Here are the web mockups:
<img width="850" alt="Screen Shot 2021-04-18 at 21 03 16" src="https://user-images.githubusercontent.com/48058901/115155788-17ca5880-a08a-11eb-986d-6538f4687caa.png">
<img width="850" alt="Screen Shot 2021-04-18 at 21 03 35" src="https://user-images.githubusercontent.com/48058901/115155793-1ef16680-a08a-11eb-82a6-c96ec15b76d9.png">
<img width="850" alt="Screen Shot 2021-04-18 at 21 03 51" src="https://user-images.githubusercontent.com/48058901/115155805-2dd81900-a08a-11eb-833d-fbb0993a18e5.png">
<img width="850" alt="Screen Shot 2021-04-18 at 21 04 06" src="https://user-images.githubusercontent.com/48058901/115155808-329ccd00-a08a-11eb-83ab-abcfa9f8334f.png">
<img width="850" alt="Screen Shot 2021-04-18 at 21 04 16" src="https://user-images.githubusercontent.com/48058901/115155814-34ff2700-a08a-11eb-85bc-c831d89c48a9.png">
<img width="850" alt="Screen Shot 2021-04-18 at 21 04 29" src="https://user-images.githubusercontent.com/48058901/115155818-39c3db00-a08a-11eb-849c-31c49d0e8bce.png">
<img width="850" alt="Screen Shot 2021-04-18 at 21 04 40" src="https://user-images.githubusercontent.com/48058901/115155822-3deff880-a08a-11eb-850a-3088cfda8f7f.png">
