### ISSUE TITLE
Create mockup (header, footer, notifications pages)

### ISSUE THREAD

**Issue by salih997** [bounswe/2021SpringGroup5#66]

**Comment by zudiay** [comment]
Maybe for web version, a sidebar would be better. What do you think?

**Comment by umutgun17** [comment]
That is perfect idea. It is user-friendly. I cared this idea while designing

**Comment by umutgun17** [comment]
1) Here it is the web header and footer templates

![events-sub-menu-soccer-hover](https://user-images.githubusercontent.com/16627402/115291368-554be600-a15d-11eb-8456-074a5117443f.png)

**Comment by umutgun17** [comment]
2) Here it is the mobile header and footer templates
![mobile-header-footer-template](https://user-images.githubusercontent.com/16627402/115291560-947a3700-a15d-11eb-9203-2049b95cc97e.png)

**Comment by umutgun17** [comment]
Also I want to add header and footer separately as png file because you can implement them on your mockups easily.

Header:
![header](https://user-images.githubusercontent.com/16627402/115291722-c390a880-a15d-11eb-9fcb-01a86ffcf135.png)

Footer:
![footer](https://user-images.githubusercontent.com/16627402/115291766-cd1a1080-a15d-11eb-93f5-ec72604e9066.png)

**Comment by umutgun17** [comment]
Equipment post page is filled with scenario text. 
![equipment-mobile-new](https://user-images.githubusercontent.com/16627402/115295154-1bc9a980-a162-11eb-8b98-8d760ca0b137.png)
![equipment-web-new](https://user-images.githubusercontent.com/16627402/115295164-1e2c0380-a162-11eb-8d79-5e6063cb5aa2.png)
